# -*- coding: utf-8 -*-
"""Real Estate Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NeFYDLtOCw_ApNfCyo3aSkYWXOjiLEGh
"""

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np
# Loading the CSV data
file_path = '/content/drive/My Drive/Real_estate.csv'
data = pd.read_csv(file_path)

# Display the first few rows of the dataset
data.head()
# Now define features (X) and target variable (y)
X = data.drop('Y house price of unit area', axis=1)
y = data['Y house price of unit area']

# Now Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Now Initializing the linear regression model
model = LinearRegression()

# Now Fit the model on the training data
model.fit(X_train, y_train)
# Making predictions on the testing set
y_pred = model.predict(X_test)

# Now model calculates evaluation metrics
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

rmse = np.sqrt(mse)

print("Mean Squared Error (MSE):", mse)
print("Mean Absolute Error (MAE):", mae)
print("Root Mean Squared Error (RMSE):", rmse)
print("R-squared (R^2):", r2)